// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FlowChart: typeof import('./src/components/FlowChart/FlowChart.vue')['default']
    FromDettail: typeof import('./src/components/FlowChart/FromDettail.vue')['default']
    RightMenu: typeof import('./src/components/FlowChart/RightMenu.vue')['default']
  }
}

export {}
